import type { ReactGrabAPI } from "../types.js";

const NOOP = () => {};

export const createNoopApi = (): ReactGrabAPI => ({
  activate: NOOP,
  deactivate: NOOP,
  toggle: NOOP,
  comment: NOOP,
  isActive: () => false,
  isEnabled: () => false,
  setEnabled: NOOP,
  getToolbarState: () => null,
  setToolbarState: NOOP,
  onToolbarStateChange: () => NOOP,
  dispose: NOOP,
  copyElement: () => Promise.resolve(false),
  getSource: () => Promise.resolve(null),
  getStackContext: () => Promise.resolve(""),
  getState: () => ({
    isActive: false,
    isDragging: false,
    isCopying: false,
    isPromptMode: false,
    isSelectionBoxVisible: false,
    isDragBoxVisible: false,
    targetElement: null,
    dragBounds: null,
    grabbedBoxes: [],
    labelInstances: [],
    selectionFilePath: null,
    toolbarState: null,
  }),
  setOptions: NOOP,
  registerPlugin: NOOP,
  unregisterPlugin: NOOP,
  getPlugins: () => [],
  getDisplayName: () => null,
  getSession: () => ({
    version: 1,
    createdAt: 0,
    startedAt: null,
    endedAt: null,
    userAgent: "",
    href: "",
    viewport: { width: 0, height: 0, scrollX: 0, scrollY: 0, devicePixelRatio: 1 },
    elements: [],
    events: [],
  }),
  replaySession: () => Promise.resolve(),
  clearEventLog: NOOP,
  setEventLogRecording: NOOP,
});
