/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 *
 * This file is generated by scripts/generate-noop-api.ts
 * To regenerate, run: pnpm generate
 */
import type { ReactGrabAPI, ReactGrabState } from "../types.js";

const NOOP = () => {};

const NOOP_STATE: ReactGrabState = {
  isActive: false,
  isDragging: false,
  isCopying: false,
  isPromptMode: false,
  isSelectionBoxVisible: false,
  isDragBoxVisible: false,
  targetElement: null,
  dragBounds: null,
  grabbedBoxes: [],
  labelInstances: [],
  selectionFilePath: null,
  toolbarState: null,
};

export const createNoopApi = (): ReactGrabAPI => ({
  activate: NOOP,
  deactivate: NOOP,
  toggle: NOOP,
  comment: NOOP,
  isActive: () => false,
  isEnabled: () => false,
  setEnabled: NOOP,
  getToolbarState: () => null,
  setToolbarState: NOOP,
  onToolbarStateChange: () => NOOP,
  dispose: NOOP,
  copyElement: () => Promise.resolve(false),
  getSource: () => Promise.resolve(null),
  getStackContext: () => Promise.resolve(""),
  getState: () => ({ ...NOOP_STATE }) as ReactGrabState,
  setOptions: NOOP,
  registerPlugin: NOOP,
  unregisterPlugin: NOOP,
  getPlugins: () => [],
  getDisplayName: () => null,
});
