export { REACT_GRAB_ATTRIBUTE_NAME as ATTRIBUTE_NAME } from "../src/utils/react-grab-attribute-name.js";

export const SHIFT_LABEL_CLICK_ANCHOR_RATIO = 0.25;
export const SHIFT_LABEL_SECOND_CLICK_ANCHOR_RATIO = 0.75;
export const SHIFT_LABEL_ANCHORED_COUNT = 2;
export const SHIFT_LABEL_POSITION_TOLERANCE_PX = 2;
export const SHIFT_LABEL_MOUSE_MOVE_INSET_PX = 10;
export const SHIFT_LABEL_SETTLE_DELAY_MS = 120;
export const SHIFT_DRAG_PREVIEW_OUTSET_PX = 10;
export const SHIFT_DRAG_PREVIEW_STEP_COUNT = 6;
export const SHIFT_PENDING_HOVER_STEP_COUNT = 8;
