import ts from "typescript";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const DIRECTORY = path.dirname(fileURLToPath(import.meta.url));
const TYPES_PATH = path.resolve(DIRECTORY, "../src/types.ts");
const OUTPUT_PATH = path.resolve(DIRECTORY, "../src/core/noop-api.ts");

const resolveReturnDefault = (
  returnType: ts.TypeNode,
  sourceFile: ts.SourceFile,
): string => {
  const text = returnType.getText(sourceFile).trim();

  if (text === "void") return "undefined";
  if (text === "boolean") return "false";
  if (text === "number") return "0";
  if (text === "string") return '""';
  if (text === "string[]") return "[]";
  if (text.endsWith("| null")) return "null";
  if (text.endsWith("| undefined")) return "undefined";
  if (text.startsWith("Promise<")) {
    const inner = text.slice("Promise<".length, -1);
    if (inner === "void") return "Promise.resolve()";
    if (inner === "boolean") return "Promise.resolve(false)";
    if (inner === "string") return 'Promise.resolve("")';
    if (inner.endsWith("| null")) return "Promise.resolve(null)";
    return "Promise.resolve(undefined as never)";
  }
  if (text === "ReactGrabState") return "NOOP_STATE";

  if (returnType.kind === ts.SyntaxKind.FunctionType || text.startsWith("(")) {
    return "NOOP";
  }

  return "undefined as never";
};

const source = fs.readFileSync(TYPES_PATH, "utf-8");
const sourceFile = ts.createSourceFile(
  "types.ts",
  source,
  ts.ScriptTarget.Latest,
  true,
);

let reactGrabApiInterface: ts.InterfaceDeclaration | undefined;
let reactGrabStateInterface: ts.InterfaceDeclaration | undefined;

ts.forEachChild(sourceFile, (node) => {
  if (ts.isInterfaceDeclaration(node) && node.name.text === "ReactGrabAPI") {
    reactGrabApiInterface = node;
  }
  if (ts.isInterfaceDeclaration(node) && node.name.text === "ReactGrabState") {
    reactGrabStateInterface = node;
  }
});

if (!reactGrabApiInterface) {
  throw new Error("Could not find ReactGrabAPI interface in types.ts");
}
if (!reactGrabStateInterface) {
  throw new Error("Could not find ReactGrabState interface in types.ts");
}

const stateDefaults: string[] = [];
for (const member of reactGrabStateInterface.members) {
  if (!ts.isPropertySignature(member) || !member.name || !member.type) continue;
  const propertyName = member.name.getText(sourceFile);
  const typeText = member.type.getText(sourceFile).trim();

  let defaultValue: string;
  if (typeText === "boolean") defaultValue = "false";
  else if (typeText === "number") defaultValue = "0";
  else if (typeText === "string") defaultValue = '""';
  else if (typeText.endsWith("| null")) defaultValue = "null";
  else if (typeText.startsWith("Array<") || typeText.endsWith("[]"))
    defaultValue = "[]";
  else defaultValue = "null as never";

  stateDefaults.push(`  ${propertyName}: ${defaultValue},`);
}

const methodEntries: string[] = [];
for (const member of reactGrabApiInterface.members) {
  if (!ts.isPropertySignature(member) || !member.name || !member.type) continue;

  const methodName = member.name.getText(sourceFile);
  const typeNode = member.type;

  if (!ts.isFunctionTypeNode(typeNode)) continue;

  const returnType = typeNode.type;
  if (!returnType) continue;

  const defaultValue = resolveReturnDefault(returnType, sourceFile);

  if (defaultValue === "undefined") {
    methodEntries.push(`    ${methodName}: NOOP,`);
  } else if (defaultValue === "NOOP_STATE") {
    methodEntries.push(
      `    ${methodName}: () => ({ ...NOOP_STATE }) as ReactGrabState,`,
    );
  } else if (defaultValue === "NOOP") {
    methodEntries.push(`    ${methodName}: () => NOOP,`);
  } else {
    methodEntries.push(`    ${methodName}: () => ${defaultValue},`);
  }
}

const output = `// AUTO-GENERATED by scripts/generate-noop-api.ts — do not edit manually
import type { ReactGrabAPI, ReactGrabState } from "../types.js";

const NOOP = () => {};

const NOOP_STATE: ReactGrabState = {
${stateDefaults.join("\n")}
};

export const createNoopApi = (): ReactGrabAPI => ({
${methodEntries.join("\n")}
});
`;

fs.writeFileSync(OUTPUT_PATH, output);
console.log(`Generated ${OUTPUT_PATH}`);
