import ts from "typescript";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const DIRECTORY = path.dirname(fileURLToPath(import.meta.url));
const TYPES_PATH = path.resolve(DIRECTORY, "../src/types.ts");
const OUTPUT_PATH = path.resolve(DIRECTORY, "../src/core/noop-api.ts");

const isNullKeyword = (node: ts.TypeNode): boolean =>
  node.kind === ts.SyntaxKind.NullKeyword ||
  (ts.isLiteralTypeNode(node) &&
    node.literal.kind === ts.SyntaxKind.NullKeyword);

const isUndefinedKeyword = (node: ts.TypeNode): boolean =>
  node.kind === ts.SyntaxKind.UndefinedKeyword ||
  (ts.isLiteralTypeNode(node) &&
    node.literal.kind === ts.SyntaxKind.UndefinedKeyword);

const isNullableUnion = (node: ts.TypeNode): boolean => {
  if (!ts.isUnionTypeNode(node)) return false;
  return node.types.some(
    (typeNode) => isNullKeyword(typeNode) || isUndefinedKeyword(typeNode),
  );
};

const isArrayType = (node: ts.TypeNode): boolean =>
  ts.isArrayTypeNode(node) ||
  (ts.isTypeReferenceNode(node) &&
    ts.isIdentifier(node.typeName) &&
    node.typeName.text === "Array");

const isPromiseType = (node: ts.TypeNode): boolean =>
  ts.isTypeReferenceNode(node) &&
  ts.isIdentifier(node.typeName) &&
  node.typeName.text === "Promise";

const getPromiseInner = (node: ts.TypeNode): ts.TypeNode | undefined =>
  isPromiseType(node) && ts.isTypeReferenceNode(node)
    ? node.typeArguments?.[0]
    : undefined;

const resolveDefault = (node: ts.TypeNode): string => {
  if (node.kind === ts.SyntaxKind.VoidKeyword) return "undefined";
  if (node.kind === ts.SyntaxKind.BooleanKeyword) return "false";
  if (node.kind === ts.SyntaxKind.NumberKeyword) return "0";
  if (node.kind === ts.SyntaxKind.StringKeyword) return '""';
  if (node.kind === ts.SyntaxKind.NullKeyword) return "null";
  if (node.kind === ts.SyntaxKind.UndefinedKeyword) return "undefined";

  if (isNullableUnion(node)) return "null";
  if (isArrayType(node)) return "[]";
  if (ts.isFunctionTypeNode(node)) return "NOOP";

  if (isPromiseType(node)) {
    const inner = getPromiseInner(node);
    if (!inner) return "Promise.resolve()";
    const innerDefault = resolveDefault(inner);
    return innerDefault === "undefined"
      ? "Promise.resolve()"
      : `Promise.resolve(${innerDefault})`;
  }

  if (ts.isTypeReferenceNode(node) && ts.isIdentifier(node.typeName)) {
    const referenceName = node.typeName.text;
    if (referenceName === "ReactGrabState") return "INLINE_STATE";
  }

  return "undefined as never";
};

const resolvePropertyDefault = (node: ts.TypeNode): string => {
  if (node.kind === ts.SyntaxKind.BooleanKeyword) return "false";
  if (node.kind === ts.SyntaxKind.NumberKeyword) return "0";
  if (node.kind === ts.SyntaxKind.StringKeyword) return '""';
  if (isNullableUnion(node)) return "null";
  if (isArrayType(node)) return "[]";
  return "null as never";
};

const source = fs.readFileSync(TYPES_PATH, "utf-8");
const sourceFile = ts.createSourceFile(
  "types.ts",
  source,
  ts.ScriptTarget.Latest,
  true,
);

const findInterface = (name: string): ts.InterfaceDeclaration => {
  let found: ts.InterfaceDeclaration | undefined;
  ts.forEachChild(sourceFile, (node) => {
    if (ts.isInterfaceDeclaration(node) && node.name.text === name) {
      found = node;
    }
  });
  if (!found) throw new Error(`Could not find interface ${name} in types.ts`);
  return found;
};

const reactGrabApiInterface = findInterface("ReactGrabAPI");
const reactGrabStateInterface = findInterface("ReactGrabState");

const stateDefaults: string[] = [];
for (const member of reactGrabStateInterface.members) {
  if (!ts.isPropertySignature(member) || !member.name || !member.type) continue;
  const propertyName = member.name.getText(sourceFile);
  stateDefaults.push(
    `  ${propertyName}: ${resolvePropertyDefault(member.type)},`,
  );
}

const methodEntries: string[] = [];
for (const member of reactGrabApiInterface.members) {
  if (!ts.isPropertySignature(member) || !member.name || !member.type) continue;

  const methodName = member.name.getText(sourceFile);
  const typeNode = member.type;

  if (!ts.isFunctionTypeNode(typeNode) || !typeNode.type) continue;

  const defaultValue = resolveDefault(typeNode.type);

  if (defaultValue === "undefined") {
    methodEntries.push(`  ${methodName}: NOOP,`);
  } else if (defaultValue === "INLINE_STATE") {
    const stateBody = stateDefaults.map((line) => `    ${line.trim()}`).join("\n");
    methodEntries.push(`  ${methodName}: () => ({\n${stateBody}\n  }),`);
  } else if (defaultValue === "NOOP") {
    methodEntries.push(`  ${methodName}: () => NOOP,`);
  } else {
    methodEntries.push(`  ${methodName}: () => ${defaultValue},`);
  }
}

const output = `/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 *
 * This file is generated by scripts/generate-noop-api.ts
 * To regenerate, run: pnpm generate
 */
import type { ReactGrabAPI } from "../types.js";

const NOOP = () => {};

export const createNoopApi = (): ReactGrabAPI => ({
${methodEntries.join("\n")}
});
`;

fs.writeFileSync(OUTPUT_PATH, output);
console.log(`Generated ${OUTPUT_PATH}`);
