import {
  FORM_CONTROLS_MAX_DIFF_RATIO,
  FORM_CONTROLS_MAX_MEAN_CHANNEL_DELTA,
  INDETERMINATE_FORM_MAX_DIFF_RATIO,
  INDETERMINATE_FORM_MAX_MEAN_CHANNEL_DELTA,
  STRICT_MAX_DIFF_RATIO,
  TRANSFORMED_ROOT_MAX_DIFF_RATIO,
  TRANSFORMED_ROOT_MAX_MEAN_CHANNEL_DELTA,
} from "./constants";
import type { FixtureSpec } from "./types";

export const fixtureManifest: FixtureSpec[] = [
  { id: "01-solid-box", maxDiffRatio: STRICT_MAX_DIFF_RATIO },
  { id: "02-borders-radius", maxDiffRatio: STRICT_MAX_DIFF_RATIO },
  { id: "03-gradients", maxDiffRatio: STRICT_MAX_DIFF_RATIO },
  { id: "04-transforms", maxDiffRatio: STRICT_MAX_DIFF_RATIO },
  { id: "10-typography", maxDiffRatio: STRICT_MAX_DIFF_RATIO },
  { id: "11-text-styles", maxDiffRatio: STRICT_MAX_DIFF_RATIO },
  { id: "20-flex-layout", maxDiffRatio: STRICT_MAX_DIFF_RATIO },
  { id: "21-grid-layout", maxDiffRatio: STRICT_MAX_DIFF_RATIO },
  { id: "30-box-shadows", maxDiffRatio: STRICT_MAX_DIFF_RATIO },
  { id: "31-filters-opacity", maxDiffRatio: STRICT_MAX_DIFF_RATIO },
  { id: "40-images", maxDiffRatio: STRICT_MAX_DIFF_RATIO },
  { id: "41-background-images", maxDiffRatio: STRICT_MAX_DIFF_RATIO },
  { id: "50-pseudo-elements", maxDiffRatio: STRICT_MAX_DIFF_RATIO },
  {
    id: "51-form-controls",
    maxDiffRatio: FORM_CONTROLS_MAX_DIFF_RATIO,
    maxMeanChannelDelta: FORM_CONTROLS_MAX_MEAN_CHANNEL_DELTA,
  },
  { id: "52-scrolled-container", maxDiffRatio: STRICT_MAX_DIFF_RATIO },
  { id: "53-shadow-dom", maxDiffRatio: STRICT_MAX_DIFF_RATIO },
  { id: "54-canvas-2d", maxDiffRatio: STRICT_MAX_DIFF_RATIO },
  { id: "55-scrolled-flex-grid", maxDiffRatio: STRICT_MAX_DIFF_RATIO },
  { id: "60-kitchen-sink", maxDiffRatio: STRICT_MAX_DIFF_RATIO },
  { id: "70-stress", maxDiffRatio: STRICT_MAX_DIFF_RATIO },
  { id: "dtim-anchor-underline-reset", maxDiffRatio: STRICT_MAX_DIFF_RATIO },
  { id: "dtim-background-clip-gloss-text", maxDiffRatio: STRICT_MAX_DIFF_RATIO },
  { id: "dtim-bare-text-node", maxDiffRatio: STRICT_MAX_DIFF_RATIO },
  { id: "dtim-bigger-repeated-strips", maxDiffRatio: STRICT_MAX_DIFF_RATIO },
  { id: "dtim-border-reset-preflight", maxDiffRatio: STRICT_MAX_DIFF_RATIO },
  { id: "dtim-canvas-text-and-zero-width", maxDiffRatio: STRICT_MAX_DIFF_RATIO },
  { id: "dtim-css-background", maxDiffRatio: STRICT_MAX_DIFF_RATIO },
  { id: "dtim-css-mask-icon", maxDiffRatio: STRICT_MAX_DIFF_RATIO },
  { id: "dtim-custom-element-slots", maxDiffRatio: STRICT_MAX_DIFF_RATIO },
  { id: "dtim-external-stylesheet", maxDiffRatio: STRICT_MAX_DIFF_RATIO },
  { id: "dtim-flex-fractional-widths", maxDiffRatio: STRICT_MAX_DIFF_RATIO },
  { id: "dtim-fontawesome-glyph", maxDiffRatio: STRICT_MAX_DIFF_RATIO },
  { id: "dtim-foreign-namespace-element", maxDiffRatio: STRICT_MAX_DIFF_RATIO },
  { id: "dtim-heading-font-size-override", maxDiffRatio: STRICT_MAX_DIFF_RATIO },
  { id: "dtim-html-anchor-attr-selector", maxDiffRatio: STRICT_MAX_DIFF_RATIO },
  { id: "dtim-icon-font-pseudo", maxDiffRatio: STRICT_MAX_DIFF_RATIO },
  { id: "dtim-images-nested", maxDiffRatio: STRICT_MAX_DIFF_RATIO },
  {
    // Native text-field chrome (border/caret/focus painting) is platform-rendered; same class as 51-form-controls.
    id: "dtim-input-user-value",
    maxDiffRatio: FORM_CONTROLS_MAX_DIFF_RATIO,
    maxMeanChannelDelta: FORM_CONTROLS_MAX_MEAN_CHANNEL_DELTA,
  },
  { id: "dtim-mathml", maxDiffRatio: STRICT_MAX_DIFF_RATIO },
  { id: "dtim-one-sided-border", maxDiffRatio: STRICT_MAX_DIFF_RATIO },
  { id: "dtim-pixel-grid-opacity", maxDiffRatio: STRICT_MAX_DIFF_RATIO },
  { id: "dtim-pseudo-background-image", maxDiffRatio: STRICT_MAX_DIFF_RATIO },
  { id: "dtim-pseudo-before-after", maxDiffRatio: STRICT_MAX_DIFF_RATIO },
  { id: "dtim-small-strips", maxDiffRatio: STRICT_MAX_DIFF_RATIO },
  { id: "dtim-srcset-active-candidate", maxDiffRatio: STRICT_MAX_DIFF_RATIO },
  { id: "dtim-svg-broken-namespace", maxDiffRatio: STRICT_MAX_DIFF_RATIO },
  { id: "dtim-svg-image-href", maxDiffRatio: STRICT_MAX_DIFF_RATIO },
  { id: "dtim-svg-rect", maxDiffRatio: STRICT_MAX_DIFF_RATIO },
  { id: "dtim-svg-use-out-of-subtree", maxDiffRatio: STRICT_MAX_DIFF_RATIO },
  { id: "dtim-table-caption-height", maxDiffRatio: STRICT_MAX_DIFF_RATIO },
  { id: "dtim-table-zero-padding", maxDiffRatio: STRICT_MAX_DIFF_RATIO },
  { id: "dtim-tailwind-preflight-card", maxDiffRatio: STRICT_MAX_DIFF_RATIO },
  { id: "dtim-text-nodes", maxDiffRatio: STRICT_MAX_DIFF_RATIO },
  { id: "dtim-textarea-user-value", maxDiffRatio: STRICT_MAX_DIFF_RATIO },
  { id: "dtim-visibility-hidden-child", maxDiffRatio: STRICT_MAX_DIFF_RATIO },
  { id: "hti-bigger", maxDiffRatio: STRICT_MAX_DIFF_RATIO },
  { id: "hti-border-em", maxDiffRatio: STRICT_MAX_DIFF_RATIO },
  { id: "hti-css-background", maxDiffRatio: STRICT_MAX_DIFF_RATIO },
  { id: "hti-external-stylesheet", maxDiffRatio: STRICT_MAX_DIFF_RATIO },
  { id: "hti-fontawesome-brand-icon", maxDiffRatio: STRICT_MAX_DIFF_RATIO },
  { id: "hti-hash-colors-attrs", maxDiffRatio: STRICT_MAX_DIFF_RATIO },
  { id: "hti-images", maxDiffRatio: STRICT_MAX_DIFF_RATIO },
  { id: "hti-input-user-value", maxDiffRatio: STRICT_MAX_DIFF_RATIO },
  { id: "hti-lazy-images", maxDiffRatio: STRICT_MAX_DIFF_RATIO },
  { id: "hti-pixel-grid", maxDiffRatio: STRICT_MAX_DIFF_RATIO },
  { id: "hti-pseudo-content", maxDiffRatio: STRICT_MAX_DIFF_RATIO },
  { id: "hti-select-options", maxDiffRatio: STRICT_MAX_DIFF_RATIO },
  { id: "hti-small-strips", maxDiffRatio: STRICT_MAX_DIFF_RATIO },
  { id: "hti-svg-broken-namespace", maxDiffRatio: STRICT_MAX_DIFF_RATIO },
  { id: "hti-svg-css-fill", maxDiffRatio: STRICT_MAX_DIFF_RATIO },
  { id: "hti-svg-image-href", maxDiffRatio: STRICT_MAX_DIFF_RATIO },
  { id: "hti-svg-rect", maxDiffRatio: STRICT_MAX_DIFF_RATIO },
  { id: "hti-svg-use-hidden-sprite", maxDiffRatio: STRICT_MAX_DIFF_RATIO },
  { id: "hti-text-nodes", maxDiffRatio: STRICT_MAX_DIFF_RATIO },
  { id: "hti-textarea-user-value", maxDiffRatio: STRICT_MAX_DIFF_RATIO },
  { id: "hti-video-poster", maxDiffRatio: STRICT_MAX_DIFF_RATIO },
  { id: "hti-webp-image", maxDiffRatio: STRICT_MAX_DIFF_RATIO },
  { id: "lim-cross-origin-font-face", maxDiffRatio: STRICT_MAX_DIFF_RATIO },
  {
    id: "lim-content-visibility-offscreen",
    maxDiffRatio: STRICT_MAX_DIFF_RATIO,
    scrollTargetIntoViewBeforeScreenshot: true,
  },
  { id: "lim-fixed-in-scrolled-page", maxDiffRatio: STRICT_MAX_DIFF_RATIO },
  { id: "lim-indeterminate-checkbox", maxDiffRatio: STRICT_MAX_DIFF_RATIO },
  {
    id: "lim-lazy-image-offscreen",
    maxDiffRatio: STRICT_MAX_DIFF_RATIO,
    scrollTargetIntoViewBeforeScreenshot: true,
  },
  {
    // bleed:"auto" resolves to 80px here (1.5 x 40px blur + 8px spread + 12px
    // y-offset), so the clip expands the element AABB by the same 80px.
    id: "lim-bleed-box-shadow",
    maxDiffRatio: STRICT_MAX_DIFF_RATIO,
    screenshotClipTargetAabb: true,
    screenshotClipExpandPx: 80,
    captureBleed: "auto",
  },
  { id: "lim-backdrop-filter", maxDiffRatio: STRICT_MAX_DIFF_RATIO },
  { id: "lim-marker-lists", maxDiffRatio: STRICT_MAX_DIFF_RATIO },
  {
    // Rotated/scaled edges and glyphs are rasterized twice (live compositor vs
    // decoded SVG image) with independently antialiased diagonals; measured
    // 0.00917 / mean 4.63 with the diff confined to the border perimeter and
    // glyph edges, so the budget ratchets just above that.
    id: "lim-transformed-root-rotated",
    maxDiffRatio: TRANSFORMED_ROOT_MAX_DIFF_RATIO,
    maxMeanChannelDelta: TRANSFORMED_ROOT_MAX_MEAN_CHANNEL_DELTA,
    screenshotClipTargetAabb: true,
  },
  {
    // Same antialiasing class as lim-transformed-root-rotated; measured
    // 0.00654 / mean 2.40 (rounded corners + text under non-uniform scale).
    id: "lim-transformed-root-scaled",
    maxDiffRatio: TRANSFORMED_ROOT_MAX_DIFF_RATIO,
    maxMeanChannelDelta: TRANSFORMED_ROOT_MAX_MEAN_CHANNEL_DELTA,
    screenshotClipTargetAabb: true,
  },
  {
    id: "lim-transformed-root-in-scaled-ancestor",
    maxDiffRatio: STRICT_MAX_DIFF_RATIO,
    screenshotClipTargetAabb: true,
  },
  { id: "ms-background-clip-text", maxDiffRatio: STRICT_MAX_DIFF_RATIO },
  { id: "ms-background-color", maxDiffRatio: STRICT_MAX_DIFF_RATIO },
  { id: "ms-background-image-jpeg", maxDiffRatio: STRICT_MAX_DIFF_RATIO },
  { id: "ms-border-em-width", maxDiffRatio: STRICT_MAX_DIFF_RATIO },
  { id: "ms-border-image", maxDiffRatio: STRICT_MAX_DIFF_RATIO },
  { id: "ms-comment-node", maxDiffRatio: STRICT_MAX_DIFF_RATIO },
  { id: "ms-css-counter", maxDiffRatio: STRICT_MAX_DIFF_RATIO },
  { id: "ms-emoji-text", maxDiffRatio: STRICT_MAX_DIFF_RATIO },
  { id: "ms-font-face-cascade-layer", maxDiffRatio: STRICT_MAX_DIFF_RATIO },
  { id: "ms-font-family-fallback", maxDiffRatio: STRICT_MAX_DIFF_RATIO },
  { id: "ms-font-icon-fa", maxDiffRatio: STRICT_MAX_DIFF_RATIO },
  { id: "ms-iframe-same-origin", maxDiffRatio: STRICT_MAX_DIFF_RATIO },
  { id: "ms-illegal-xml-characters", maxDiffRatio: STRICT_MAX_DIFF_RATIO },
  {
    // The broken <img> paints Chromium's native broken-image glyph; captures render it empty — chrome divergence, not fidelity.
    id: "ms-img-formats-and-broken",
    maxDiffRatio: FORM_CONTROLS_MAX_DIFF_RATIO,
    maxMeanChannelDelta: FORM_CONTROLS_MAX_MEAN_CHANNEL_DELTA,
  },
  { id: "ms-malformed-attribute", maxDiffRatio: STRICT_MAX_DIFF_RATIO },
  { id: "ms-margin", maxDiffRatio: STRICT_MAX_DIFF_RATIO },
  { id: "ms-mask-image-svg", maxDiffRatio: STRICT_MAX_DIFF_RATIO },
  { id: "ms-max-height-important-override", maxDiffRatio: STRICT_MAX_DIFF_RATIO },
  { id: "ms-nested-shadow-dom", maxDiffRatio: STRICT_MAX_DIFF_RATIO },
  { id: "ms-pseudo-content-custom-font", maxDiffRatio: STRICT_MAX_DIFF_RATIO },
  { id: "ms-svg-broken-namespace", maxDiffRatio: STRICT_MAX_DIFF_RATIO },
  { id: "ms-svg-css-fill-foreignobject", maxDiffRatio: STRICT_MAX_DIFF_RATIO },
  { id: "ms-svg-external-symbol", maxDiffRatio: STRICT_MAX_DIFF_RATIO },
  { id: "ms-svg-in-shadow-dom", maxDiffRatio: STRICT_MAX_DIFF_RATIO },
  { id: "ms-svg-rect", maxDiffRatio: STRICT_MAX_DIFF_RATIO },
  { id: "ms-svg-symbol-currentcolor", maxDiffRatio: STRICT_MAX_DIFF_RATIO },
  { id: "ms-text-stroke", maxDiffRatio: STRICT_MAX_DIFF_RATIO },
  {
    // Native textarea chrome (resizer grip, control painting); same class as 51-form-controls.
    id: "ms-textarea",
    maxDiffRatio: FORM_CONTROLS_MAX_DIFF_RATIO,
    maxMeanChannelDelta: FORM_CONTROLS_MAX_MEAN_CHANNEL_DELTA,
  },
  { id: "ms-video-poster", maxDiffRatio: STRICT_MAX_DIFF_RATIO },
  { id: "ms-webkit-scrollbar", maxDiffRatio: STRICT_MAX_DIFF_RATIO },
  { id: "snap-blob-urls", maxDiffRatio: STRICT_MAX_DIFF_RATIO },
  { id: "snap-content-visibility", maxDiffRatio: STRICT_MAX_DIFF_RATIO },
  { id: "snap-css-counters", maxDiffRatio: STRICT_MAX_DIFF_RATIO },
  { id: "snap-css-variables", maxDiffRatio: STRICT_MAX_DIFF_RATIO },
  {
    // The indeterminate dash is reproduced by a pixel replica (JS-only property,
    // no markup equivalent), so the budget ratchets to just above the remaining
    // native text-field/select/textarea chrome divergence as in 51-form-controls.
    id: "snap-form-values-indeterminate",
    maxDiffRatio: INDETERMINATE_FORM_MAX_DIFF_RATIO,
    maxMeanChannelDelta: INDETERMINATE_FORM_MAX_MEAN_CHANNEL_DELTA,
  },
  { id: "snap-icon-font-ligature", maxDiffRatio: STRICT_MAX_DIFF_RATIO },
  { id: "snap-individual-transforms", maxDiffRatio: STRICT_MAX_DIFF_RATIO },
  { id: "snap-invalid-xml-chars", maxDiffRatio: STRICT_MAX_DIFF_RATIO },
  { id: "snap-line-clamp", maxDiffRatio: STRICT_MAX_DIFF_RATIO },
  { id: "snap-mask-longhands", maxDiffRatio: STRICT_MAX_DIFF_RATIO },
  { id: "snap-outline-no-border", maxDiffRatio: STRICT_MAX_DIFF_RATIO },
  { id: "snap-picture-srcset", maxDiffRatio: STRICT_MAX_DIFF_RATIO },
  { id: "snap-pre-margins", maxDiffRatio: STRICT_MAX_DIFF_RATIO },
  { id: "snap-pseudo-after-inline-position", maxDiffRatio: STRICT_MAX_DIFF_RATIO },
  { id: "snap-pseudo-border-spacer", maxDiffRatio: STRICT_MAX_DIFF_RATIO },
  { id: "snap-pseudo-first-letter", maxDiffRatio: STRICT_MAX_DIFF_RATIO },
  { id: "snap-shadow-css-vars", maxDiffRatio: STRICT_MAX_DIFF_RATIO },
  { id: "snap-sticky-in-scroll", maxDiffRatio: STRICT_MAX_DIFF_RATIO },
  { id: "snap-svg-defs-gradient-use", maxDiffRatio: STRICT_MAX_DIFF_RATIO },
  { id: "snap-table-cell-widths", maxDiffRatio: STRICT_MAX_DIFF_RATIO },
  { id: "snap-video-poster-fallback", maxDiffRatio: STRICT_MAX_DIFF_RATIO },
  { id: "snap-width-softening-boxes", maxDiffRatio: STRICT_MAX_DIFF_RATIO },
  { id: "snap-zero-width-borders", maxDiffRatio: STRICT_MAX_DIFF_RATIO },
];
